name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check package version
        id: check
        uses: 'EndBug/version-check@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Create release
        uses: 'zendesk/action-create-release@v1'
        if: ${{ steps.check.outputs.changed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check.outputs.version}}
          release_name: v${{ steps.check.outputs.version}}
          draft: false
          prerelease: false
